### PR TITLE
COB Release 2 Nov

### PR DESCRIPTION
**Pull request by matentzn**
Changes:

- Replacing NCBITaxon:root class with "cellular organism" and "virus"
- Adding exposure to entity class

### CODE REVIEW

**Review by wdduncan — APPROVED** [review]

**Comment by wdduncan** [comment]
Fixes #210 

The PR has been approved. Is there documentation on what needs to be done to make the release?

**Comment by matentzn** [comment]
I can run a release but at least I would like a Chris approval, or some explicit statement about what is needed at minimum for a COB release.. I think a single review cant be enough for something as important as the one upper ontology for all of OBO..

**Comment by wdduncan** [comment]
@matentzn  Gotcha :)  
I didn't realize we were waiting @cmungall approval.

**Comment by cmungall** [comment]
It looks like this PR is just for derived files, there is no COB content changes (cob-edit or cob-to-external) here, correct?

If so I should not be a blocker for this, in fact ideally this should be done by github actions.

**Pull request merged**
