### PR TITLE
information + planned process

### PR DESCRIPTION
**Pull request by bpeters42**
Added classes, axioms, and relations from IAO and OBI to capture how information and planned processes are modeled there. Added also edits made during the COB workshop call 9/1.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
@beckyjackson Please move these edits into `cob-edit.owl`

**Comment by bpeters42** [comment]
I did not use proper COB IDs for the newly added classes and relations, but used the labels as IDs (sorry). Also I directly added the 'based on' relations, rather than editing cob-to-external.

**Comment by bpeters42** [comment]
IIf this is too much of a mess, then I can do it properly, in the right file, using correct IDS etc. I was in a rush to get it all in.

**Comment by beckyjackson** [comment]
No worries, I moved everything to `cob-edit.owl` and added the correct IDs.

**Pull request merged**
