### PR TITLE
Remove inverseOf class axioms

### LINKED ISSUE #229: Avoid use of "inverse(Property)" expression in class expressions in favour of providing an inverse relation
We rely a lot on ELK, and this kind of axiom, using complex property expressions in class expressions will result in incomplete reasoning:

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/COB_0000113">
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty>
                    <rdf:Description>
                        <owl:inverseOf rdf:resource="http://purl.obolibrary.org/obo/COB_0000087"/>
                    </rdf:Description>
                </owl:onProperty>
                <owl:allValuesFrom rdf:resource="http://purl.obolibrary.org/obo/COB_0000082"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:label xml:lang="en">plan</rdfs:label>
    </owl:Class>
```

I would like to propose to avoid use of "inverse(Property)" expression in class expressions in favour of providing a named inverse relation. Apart from the fact that we can actually use the expression for reasoning, it is much easier to read, and also better supported by ontology formats that are not OWL (OBO, obographs-json).

### PR DESCRIPTION
**Pull request by sebastianduesing**
Closes #229. Replaces inverseOf class axioms with genuine inverse relations.

### CODE REVIEW

**Comment by cmungall** [comment]
sorry did I merge the other one too quickly...?

**Comment by sebastianduesing** [comment]
@cmungall Nope, it's all good! I created that PR because I noticed the genid issue while making this PR—I deleted one axiom comment annotation here because the change to InverseOf rendered the comment unnecessary, then noticed it fixed the genid problem for that term, so I opened up that other PR to fix the rest of the genids.

**Comment by sebastianduesing** [comment]
At least, that's a no on the technical side—not sure if there was any desire to review it.

**Review by matentzn — APPROVED** [review]
The spurious diff is actual just an RDF re-ordering issue, so it looks great! Can merge.

**Comment by sebastianduesing** [comment]
Great, thanks!

**Pull request merged**
