### PR TITLE
Added "device"

### PR DESCRIPTION
**Pull request by ddooley**
To address https://github.com/OBOFoundry/COB/issues/222 .  Also added "has function" and "function of", understanding that ultimately they will be imported from RO.

Note domain of "has function" is an 'independent continuant' but COB doesn't have that so are we needing a disjunction of top-level terms to reflect comparable logic?

### CODE REVIEW

**Comment by ddooley** [comment]
I don't know why the cob-edit.owl diff is different.  I'm using latest protege 5.6.1.  Its coding <owl:annotatedTarget rdf:nodeID="genid58"/> outside of classes they are mentioned in.  Maybe that's normal now?!

**Comment by cmungall** [comment]
We need to have this in the CONTRIBUTING.md but PRs like this should always have corresponding edits to cob-to-external

**Review by cmungall — CHANGES_REQUESTED** [review]
can be merged when spurious diffs resolves (note cob has not been 5.6.1 normalized yet) and when cob-to-ext changes in

**Comment by matentzn** [comment]
- [ ] @cmungall as per #222 there should not be an external mapping for this term.
- [ ] @ddooley can you rename the PR? it seems has function is NOT added
- [X] I fixed the spurious diff

**Comment by ddooley** [comment]
I've renamed. Forgot that there was shift to using "has characteristic" rather than "has function".

**Comment by cmungall** [comment]
Go ahead and merge if this is a blocker but I think we need a new SOP for NTRs that replace OBO IDs

proposed here:

- #232

**Pull request merged**
