### PR TITLE
Using sssom-py for cob-external.tsv

### PR DESCRIPTION
**Pull request by matentzn**
This is replacing the old tsv2rdf.pl with sssom-py  (see #115). This will induce some pretty significant changes, in particular:

1. SSSOM metadata on OWL axioms (OWL axiom annotations)
2. Curie map in cob-external.tsv, which is required by SSSOM spec

In general this is not mergeable yet because I have some issues with the sssom-py rdf representation which I need to deal with first. I will try to fix the perl script now in a second PR so you can continue to work.

### CODE REVIEW

**Comment by matentzn** [comment]
I know added the actual ttl and owl exports of sssom-py to this, and @cmungall and I need need to fix them before we can use this.

**Comment by matentzn** [comment]
Also, having rows without predicate and object_ids will be malformed in sssom.. So we (@cmungall and me) need to consider how to handle this case.

**Comment by matentzn** [comment]
When merging this, make a ticket to change the sssom dependency and assign to me.

**Comment by matentzn** [comment]
@cmungall has looked at this and has signed off on the relevant changes.

**Comment by jamesaoverton** [comment]
Since I had trouble with the Perl script, I wanted this to be done in a more standard way. Now it seems that this isn't really what SSSOM is for -- in particular it doesn't like empty mappings that we were using as placeholders. Nico made it work.

I still think that the ROBOT template in #96 was better, but I don't want to argue about this. I'll just merge.

**Pull request merged**
