### PR TITLE
Update cob-to-external.owl

### PR DESCRIPTION
**Pull request by sebastianduesing**
Update with ROBOT version 1.9.5 and SSSOM version 0.4.4 without changing cob-to-external.tsv.

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]
This just freshens the OWL file, so our PRs will be cleaner.

**Review by matentzn — APPROVED** [review]
@sebastianduesing 

During a larger refactor sssom-py lost the ability to correctly process the `sssom:superClassOf` predicates. You PR revealed this - I have fixed it now and pushed an update.

I have put in a fix in sssom toolkit and will make a release - that will happen in the next days. But the ODK version will only be updated a little bit later in the April.

Sorry about that!

**Comment by sebastianduesing** [comment]
@matentzn Thanks for catching and fixing that! I'd wondered why sssom:superClassOf was showing up in the diff.

**Comment by jamesaoverton** [comment]
After updating to SSSOM 0.4.5 this PR become trivial: just changing the dates. So I'll just close this without merging. Thanks @matentzn!

**Pull request closed without merging**
